import { FaUser, FaRobot } from 'react-icons/fa';

/**
 * A single chat bubble in the AI Planner conversation — mirrors the
 * left/right, colored-vs-neutral bubble pattern people expect from
 * chat-style assistants (user on the right, assistant on the left).
 */
export default function ChatMessage({ role, content, source }) {
  const isUser = role === 'user';

  return (
    <div className={`flex gap-3 ${isUser ? 'flex-row-reverse' : ''}`}>
      <div
        className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 text-sm
          ${isUser ? 'bg-primary text-white' : 'bg-neutral-light text-primary'}`}
      >
        {isUser ? <FaUser /> : <FaRobot />}
      </div>

      <div className={`max-w-[80%] ${isUser ? 'items-end' : 'items-start'} flex flex-col`}>
        <div
          className={`rounded-2xl px-4 py-2.5 text-sm leading-relaxed whitespace-pre-line
            ${isUser
              ? 'bg-primary text-white rounded-tr-sm'
              : 'bg-neutral-light text-neutral-dark rounded-tl-sm'}`}
        >
          {content}
        </div>
        {!isUser && source && (
          <span className="text-[11px] text-gray-400 mt-1 px-1">
            {source === 'groq' ? 'Generated by AI' : 'Offline mode'}
          </span>
        )}
      </div>
    </div>
  );
}